#+title: titolo
#+Author: Lorenzo Macelloni
#+bibliography: biblio.bib
#+LATEX_CLASS: article
#+latex_header: \usepackage[scaled]{inter} \renewcommand\familydefault{\sfdefault}
#+latex_header: \usepackage{setspace} \onehalfspacing
#+latex_header: \usepackage{geometry} \geometry{a4paper, top=2.5cm, bottom=2.5cm, left=3.5cm, right=2.5cm }

# #+SETUPFILE: jake-standard-latex-export.org




* Abstract

* Introduzione
*** Terminologia - sesso, genere, identità di genere, orientamento sessuale
Nella discussione di una condizione come l'Incongruenza di Genere (IG) è
opportuno prendere familiarità con una determinata terminologia. Spesso infatti
alcuni termini come "sesso" e "genere" vengono utilizzati in maniera
interscambiabile nel linguaggio comune, considerando quindi inevitabilmente
correlate quelle che sono le caratteristiche socioculturali e biologiche che
contraddistinguono uomo e donna.
Negli anni l'evoluzione degli studi di genere e della teoria queer hanno portato ad una visione più moderna ed amplia di questi concetti [cite:@naples_gender_2020].
Vediamo quindi quelle che sono le definizioni date dall'NIH per questi concetti
[cite:@noauthor_sex_2022] [cite:@noauthor_sex_nodate]
# non so se è redundant citare il secondo che è citato dal primo
# also forse dovrei sostituire con le definizioni dell'APA (che penso siano le stesse)

**** Sesso Biologico
Costrutto utilizato per descrivere caratteristiche ormonali, genetiche, anatomiche e biologiche basilari.
Tipicamente è dicotomico, distingue le categorie maschio e femmina.
Tuttavia, esistono anche stati intersessuali, in cui i caratteri ed i cromosomi sessuali non sono definibili all'interno di una sola di queste categorie.
# Tra le condizioni più comuni che determinano questo stato si possono citare la Sd di Klinefelter e la Sd di Morris

**** Genere (gender)
Costrutto multidimensionale sociale e culturale; comprende ruoli, attività, comportamenti ed espressioni, che sono tipicamente identificati all'interno di una determinata società come propriamente maschili o femminili.

Sulla base del genere si definisce l'*identità di genere*.
Questa è la sensazione individuale di sentirsi parte di una determinata categoria di genere, che può essere maschile, femminile, o stati alternativi e non-binari.
L'identità di genere è quindi auto-definita, può cambiare nel corso della vita e non corrisponde necessariamente a quelle che sono le aspettative sociali nei confronti del sesso dell'individuo.
# questa roba dell'identità poi ovviamente l'approfondisco nella parte sulla storia dell'IG no? cioé mi sembra inutile stare a fare troppa intro in questa parte solo di terminologia.
Queste costituiscono infatti il *ruolo di genere*, ovvero ciò che viene percepito all'interno di una determinata società come proprio di un certo genere, in termini di norme, comportamenti ed espressioni.
L'*espressione di genere* è quindi la modalità in cui l'individuo decide di mostrare la propria identità di genere attraverso caratteristiche esterne come il proprio abbigliamento, l'utilizzo di determinati pronomi...

**** Orientamento Sessuale [cite:@NAP26424]
# qua se ho un po'parlato della cosa in vari punti dove dovrei metterla la citazione? all'inizio? in un punto a caso?

L'orientamento sessuale è anch'esso un costrutto complesso che comprende l'attrazione romantica, emotiva e sessuale.
Fa riferimento quindi agli elementi esterni capaci di indurre una risposta nell'individuo.
È quindi definito solitamente sulla base del genere delle persone verso cui un individuo prova attrazione sessuale o romantica, in rapporto al genere dell'individuo stesso.
# decisamente troppo convuluta sta frase

I termini più comuni che identificano l'orientamento sessuale di basano su una visione binaria del genere e distinguono quindi persone /eterosessuali/, /omosessuali/ e /bisessuali/.
In tempi relativamente recenti sono stati aggiunti termini che prendono in considerazione una visione più moderna e fluida del genere, come /pansessuale/ che indica un'attrazione verso gli altri che non dipende dal genere.

L'orientamento sessuale, inoltre, così come il genere, non è binario, ma costituisce uno spettro.
Il primo a prendere in considerazione questa caratteristica fluida della sessualità fu Alfred Kinsey, nel suo libro /Sexual Behavior in the Human Male/ del 1948, dove introduce la scala omonima [cite:@noauthor_kinsey_2024].
Questa definisce l'orientamento sessuale secondo un gradiente da 0, esclusiva eterossessualità, a 6, esclusiva omosessualità.

L'orientamento sessuale inoltre viene considerato fluido anche nel tempo, infatti questo può cambiare durante la vita di una persona anche in funzione delle circostanze dell'individuo.
# se ha senso aggiungere di più devo trovare un qualcosa di sensato da citare

# valutare se aggiungere la parte che divide l'orientamento in attrazione/identità/comportamento, a me sembra un po'overkill


**** Transgender e Gender Diverse
Transgender è l'aggettivo utilizzato per riferirsi ad una persona la cui identità, espressione e/o ruolo di genere non sono conformi con quello che è culturalmente associato al loro sesso biologico.
Alcuni individui non si identificano in un genere che rientra nella tipica dicotomia maschio/femmina, utilizzano quindi termini come /gender-fluid/ o /nonbinario/. [cite:@american_psychiatric_association_diagnostic_2024]

Spesso in letteratura, per riferirsi in modo più inclusivo possibile alla popolazione di tutti gli individui la cui identità di genere non corrisponde col sesso assegnato alla nascita, si utilizza il termine /transgender e gender diverse/ (TGD)[cite:@coleman_standards_2022]






*** Incongruenza di genere, cenni storici di medicina di genere

*** Epidemiologia
Nella discussione epidemiologica dei dati che riguardano la popolazione TGD è preferibile evitare i termini "incidenza" e "prevalenza", questi infatti potrebbero sottointendere in maniera impropria una condizione patologica. Oltretutto, il termine "incidenza" non è utilizzabile anche perché indica la presenza di un chiaro momento di comparsa dello status TGD, il quale è raramente individuabile.
Si preferiscono quindi i termini "numero" e "proporzione", per riferirsi alla dimensione assoluta e relativa della popolazione TGD. [cite:@coleman_standards_2022]


Nonostante un interesse crescente da parte della ricerca nei confronti della salute di questa popolazione, ci sono ancora molti dati epidemiologici anche basilari sui quali si ha poca certezza.
Le stime riportate in vari studi sono infatti fortemente dipendenti dal tipo di metodologia utilizzata per l'indagine e dalla definizione data del termine transgender.
A seconda delle pubblicazioni vengono presi in considerazione certe volte solamente color che hanno richiesto o intrapreso un percorso chirurgico di riassegnazione del sesso, altri prendono in considerazione le diagnosi di disforia di genere, mentre diversi studi svolti tramite sondaggio nella popolazione generale prendono in considerazione l'autoidentificazione come transgender.
[cite:@collin_prevalence_2016]

Per quanto riguarda nello specifico la diagnosi clinica di disforia di genere, il DSM-5-TR riporta una prevalenza tra il 0,005-0,014% per le persone AMAB e tra il 0,002% e 0,003% per le AFAB, già puntualizzando però come reputi il dato verosimilmente sottostimato.
# in questo caso è possibile utilizzare il termine prevalenza dato che si fa riferimento ad un'effettiva condizione patologica riconosciuta

[cite:@noauthor_gender_2022]
Questa stima infatti prende in considerazione solamente la parte della popolazione TGD che ha ricevuto a tutti gli effetti una diagnosi, per cui appare evidente come questo numero sia sottostimato di diversi ordini di grandezza rispetto ai sondaggi nella popolazione, i quali utilizzano criteri più generici.

# volendo mettere qua un altro studio esempio, quello nella tesi di alessio è un po'vecchio

Prendendo in considerazione i sondaggi condotti nella popolazione che utilizzano definizioni simili, i risultati sono consistenti.
Questionari che indagavano nello specifico il termine "transgender" rilevavano una stima che va tra lo 0,3% e lo 0,5% tra gli adulti e tra l'1,2% e il 2,7% tra bambini ed adolescenti.
Utilizzando una definizione più ampia che include termini come "incongruenza di genere" o "ambivalenza di genere" la percentuale aumenta a 0,5-4,5% tra gli adulti e 2,5-8,4% nella popolazione adolescente e pediatrica.
[cite:@zhang_epidemiological_2020]

La dimensione di questa popolazione è inoltre in aumento, su questo concordano sostanzialmente tutte le pubblicazioni che prendono in considerazione l'evoluzione del trend negli anni, indipendentemente da area geografica e modalità di indagine.
[cite:@goodman_size_2019]


# altri potenzialmente interessanti: - https://www.publish.csiro.au/sh/sh17067 (zuker → mi sembra di averlo visto citato) - https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0299373 (questo me lo ha dato GPT però sembra carino)

Per quanto riguarda l'Italia, uno studio del 2023 condotto tramite un sondaggio online diffuso attraverso vari social media, riporta che su 19572 partecipanti il 7,7% riporta un'identità di genere diversa dal sesso assegnato alla nascita. [cite:@fisher_estimate_2024]
Si è anche valutato come i partecipanti TGD avessero un'età media significativamente inferiore rispetto a quelli cisgender.
Inoltre è interessante notare come tra le persone TGD solamente il 41,6% riportavano un'identita di genere binaria, mentre il 58,4% si identificavano come non-binari.
# volendo aggiungere il fatto che i non binari tendenzialmente hanno meno bisogno di interventi, cambio di nome etc..?

# maybe aggiungere dopo una parte più specifica sull'epidemiologia della disforia di genere come diagnosi clinica che ne parlo un po'poco






*** Eziologia

Attualmente non sono ancora stati identificati dei chiari fattori eziologici determinanti nell'insorgenza di una incongruenza di genere.
Come molte altre patologie, l'ipotesi più attuale comprende l'interazione tra molteplici fattori di tipo biologico, genetico e psicosociale.

**** Fattori Neurologici
Il coinvolgimento neurologico si basa sull'ipotesi che i soggetti transgender abbiano delle differenze nello sviluppo dei circuiti cerebrali, rispetto ai cisgender, e che questo sia determinante nell'insorgenza dell'incongruenza di genere.
La base biologica di questa teoria è la differenza già nota tra cervello maschile e femminile nei soggetti cisgender; questa si presenta sia in un leggero vantaggio dell'uno o l'altro sesso in alcuni task cognitivi, sia in una vera e propria differenza anatomica di trofismo di alcune zone cerebrali piuttosto che altre. [cite:@miller_new_2014]

Sono diversi i fattori che intervengono nel determinare queste differenze e non tutti sono conosciuti; sicuramente è presente un'influenza ambientale, com'è reso evidente dal fatto che queste differenze tra maschi e femmine sono diverse in diverse aree geografiche, è molto probabile anche un ruolo degli ormoni sessuali durante sviluppo, infatti le differenze di trofismo sono state associate ad aree con diversa quantità di recettori estrogenici e androgenici nelle varie aree cerebrali. [cite:@goldstein_normal_2001]

Per quanto riguarda la popolazione TGD, seppur siano state dimostrate alcune differenze strutturali e funzionali nel cervello degli individui TGD, non è ancora stato indiviuato in letteratura un pattern preciso che si possa associare chiaramente a determinati cambiamenti strutturali.
Alcuni studi dimostrano come la morfologia cervello di individui con incongruenza di genere sia complessivamente più simile ad individui cisgender del sesso assegnato alla nascita rispetto a individui cisgender dell'identità di genere scelta [cite:@frigerio_structural_2021].
Tuttavia esiste anche evidenza discordante, ad esempio gli studi riguardanti la struttura della materia bianca tedono a concordare sull'esistenza di un fenotipo intermedio negli individui transgender, differente da quello di entrambi maschi e femmine cisgender[cite:@mueller_transgender_2017] [cite:@guillamon_review_2016][cite:@manzouri_possible_2019].

# volendo aggiungere? https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7750413/

Complessivamente è difficile giungere a conclusioni chiare, gli studi infatti sono limitati dall'uso di metodiche di imaging non invasive e popolazioni di piccole dimenioni; oltretutto molti prendono in considerazione sia l'identità di genere che l'orientamento sessuale, rendendo difficile differenziare chiaramente l'influenza delle due variabili.



**** Fattori Genetici
Diversi studi ipotizzano la presenza di una componente genetica nella costruzione dell'identità di genere quindi dell'incongruenza, tuttavia al momento non sono stati trovati geni specifici direttamente coinvolti.

Diversi studi sono stati condotti su gemelli monozigoti, mettendo in evidenaza come questi abbiano un tasso di concordanza maggiore sia per quanto riguarda l'identità sia per l'incongruenza di genere. [cite:@kauffman_concordance_2022] [cite:@diamond_transsexuality_2013]

Uno studio ha studiato invece il potenziale ruolo dei geni coinvolti nel /signaling/ degli ormoni sessuali, mettendo in evidenza come alcune varianti genetiche siano correlate all'incongruenza di genere in alcuni pazienti AMAB, facendo anche valutazioni ed ipotesi sul meccanismo di azione degli specifici polimorfismi. [cite:@foreman_genetic_2019]

# volendo c'è un articolo di fi che cita i cromosomi sessuali, però sostanzialmente dice che quelli con la Klinefelter hanno più GD, ma più perché sono autistici che perché sono klinefelter quindi boh mi sembra misleading mettere questo discorso qua come l'ha messo alessioMarrucci [cite:@fisher_hypersexuality_2015]
# volendo questo articolo rivede un po' la cosa https://link.springer.com/article/10.1007/s10519-018-9889-z#Sec13


**** Fattori Endocrini
???
# qualcosa nella tesi di alessio marrucci ma non mi piace come è fatto perché sono sostanzialmente fattori genetici, o lo includo in quelli oppure devo trovare altro da dire


**** Fattori Psicologici e Sociali

La maggior parte degli studi prende in considerazione il probabile intervento di vari fattori psicologici nella genesi dell'identità di genere e quindi dell'incongruenza, diverse teorie psicologiche identificano elementi differenti che potrebbero agire in diverse fasi della vita dell'individuo.

La teoria più primitiva è quella /psicodinamica/, che si rifa addirittura alla teoria Freudiana dell'identificazione, ipotizzando un intervento importante dell'esperienza infantile nella determinazione dell'identità di genere. Secondo la "teoria dell'identificazione" di Freud il bambino tende ad identificarsi con il genitore del sesso opposto in quello che è il complesso di Edipo. [cite:@benjamin_father_1991]
Nonostante ancora non venga espresso chiaramente il concetto di incongruenza di genere, è chiaro come questi concetti sottointendano l'ipotesi di una certa variabilità e fluidità nell'identità di genere.

La successiva teoria /psicosociale/ prende invece in considerazione l'intervento di fattori ambientali e culturali nella determinazione dell'identità di genere.
# fino qua ho preso praticamente la tesi di lorenzo auricchio, poi lui inizia a citare paper a caso quindi ho cercato di rivedere un po'

L'apprendimento del comportamento e ruolo di genere avvengono tramite l'osservazione e l'imitazione nel contesto sociale, andando a replicare quelli che sono i comportamenti considerati adeguati al proprio sesso, in un procedimento graduale che si sviluppa negli anni [cite:@steensma_gender_2013].
Nella popolazione TGD verosimilmente lo sviluppo della propria identità di genere avviene in modo anologo, con simili fattori determinanti,[cite:@mehrtens_transgender_2023] tuttavia, uno studio sulla popolazione pediatrica ha individuato un possibile rallentamento nell'acquisizione di un'identità di genere stabile in bambini che riconoscono un'identità di genere non corrispondente al proprio sesso biologico[cite:@zucker_gender_1999].
Un ruolo importante è anche attribuito alla presenza nell'ambiente familiare e sociale di una pressione sul bambino a comportarsi in maniera conforme al proprio sesso biologico. Questa insistenza si riflette negativamente sull'adattamento psicologico del bambino, motivo per cui si reputa al contrario ottimale un ambiente in cui il bambino possa sentirsi libero sia di confermare la propria appartenenza al sesso biologico, sia gli venga data la possibilità di esplorare identità di genere alternative. [cite:@egan_gender_2001]


#+latex: % nella tesi di lorenzo auricchio c'è una parte sul trauma però io non ho trovato niente di articoli, nemmeno quelli citati da lui ne parlano (non dicono quello che c'è scritto...)


*** Criteri Diagnostici - DSM-5-TR e ICD-11
# controllare traduzioni → non ho mai controllato i punti delle varie diagnosi

Nel discutere i criteri diagnostici nella popolazione TGD è bene rimarcare la differenza tra i termini incongruenza di genere e disforia di genere.
# presumo di aver già detto qualcosa su questo nella sezione prima per quello rimarcare

L'*incongruenza di genere* è il termine utilizzato dalla International Classification of Diseases (ICD-11), questa è caratterizzata dalla presenza di una dissonanza tra l'esperienza di genere ed il sesso biologico assegnato alla nascita. L'incongruenza di genere abbraccia in maniera più ampia la popolazione TGD e non indica una condizione patologica o disturbo psichiatrico, tanto da essere trasferita nell’ICD-11 dalla categoria dei disordini mentali a quella relativa le condizioni di salute sessuale[cite:@noauthor_icd-11_nodate].

La *disforia di genere* invece viene diagnosticata secondo i criteri del Diagnostic and Statistical Manual of Mental Disorders (DSM-5-TR), in questo caso quindi viene identificata una condizione patolgica di sofferenza, determinata dall'incongruenza tra il genere esperito ed il sesso biologico. [cite:@american_psychiatric_association_diagnostic_2022]

Data l'evoluzione di entrambe queste condizioni nella vita di un individuo, entrambe queste pubblicazioni utilizzano criteri diversi per i bambini e per adolescenti e adulti.

# quante volte devo citare il DSM e l'ICD qua? cioé è ovvio che sto prendendo tutto da questi

**** Criteri Diagnostici nei Bambini

# AGGIUNGERE CITAZIONE → non capisco come citare sottosezioni dell'ICD o DSM quindi poi dopo devo sistemare citazioni a tutto questo
# DSM sono riuscito a scaricarlo e citarlo

La definizione dell'ICD-11 dell'incongruenza di genere nei bambini:
# copiato da alessio marrucci
#+BEGIN_QUOTE
Marcata discrepanza tra il  genere sperimentato/espresso da un individuo e il sesso assegnato nei bambini prepuberali.  Questo include un forte desiderio di essere di un genere diverso rispetto al sesso assegnato; una  forte avversione da parte del bambino verso la sua anatomia sessuale o le caratteristiche sessuali  secondarie anticipate e/o un forte desiderio che le caratteristiche sessuali primarie e/o secondarie  anticipate che corrispondano al genere sperimentato; giochi, giocattoli, attività e compagni di  gioco fittizi o fantasiosi tipici del genere sperimentato piuttosto che del sesso assegnato. La discrepanza deve persistere per circa 2 anni.
#+END_QUOTE


# Gender incongruence of childhood is characterised by a marked incongruence between an individual’s experienced/expressed gender and the assigned sex in pre-pubertal children. It includes a strong desire to be a different gender than the assigned sex; a strong dislike on the child’s part of his or her sexual anatomy or anticipated secondary sex characteristics and/or a strong desire for the primary and/or anticipated secondary sex characteristics that match the experienced gender; and make-believe or fantasy play, toys, games, or activities and playmates that are typical of the experienced gender rather than the assigned sex. The incongruence must have persisted for about 2 years. Gender variant behaviour and preferences alone are not a basis for assigning the diagnosis.


I criteri diagnostici nel DSM-5 per la disforia di genere nei bambini:
A. Una marcata incongruenza tra il genere esperito/espresso da un individuo e  le caratteristiche sessuali e il genere assegnato, della durata di almeno 6 mesi, che si  manifesta attraverso almeno sei dei seguenti criteri:
   1. Un forte desiderio di appartenere al genere opposto o insistenza sul fatto di  appartenere al genere opposto (o un genere alternativo diverso dal genere  assegnato).
   2. Nei bambini, una forte preferenza per il travestimento con abbigliamento tipico  del genere opposto o per la simulazione dell’abbigliamento femminile; nelle  bambine, una forte preferenza per l’indossare esclusivamente abbigliamento  tipicamente maschile e una forte resistenza a indossare abbigliamento  tipicamente femminile.
   3. Una forte preferenza per i ruoli tipicamente legati al genere opposto nei giochi  del “far finta” o di fantasia.
   4. Una forte preferenza per giocattoli, giochi o attività stereotipicamente utilizzati o  praticati dal genere opposto.
   5. Una forte preferenza per compagni di gioco del genere opposto.
   6. Nei bambini, un forte rifiuto per giocattoli, giochi e attività tipicamente maschili, e  un forte evitamento dei giochi in cui ci si azzuffa; nelle bambine, un forte rifiuto di  giocattoli, giochi e attività tipicamente femminili.
   7. Una forte avversione per la propria anatomia sessuale.
   8. Un forte desiderio per le caratteristiche sessuali primarie e/o secondarie  corrispondenti al genere esperito.
B. La condizione è associata a sofferenza clinicamente significativa o a  compromissione del funzionamento in ambito sociale, scolastico o altre aree  importanti.

**** Criteri Diagnostici in Adulti e Adolescenti


La definizione dell'ICD-11 dell'incongruenza di genere in adulti e adolescenti:

#+BEGIN_QUOTE
Marcata e persistente  incongruenza tra il genere sperimentato da un individuo e il sesso assegnato, che spesso porta  al desiderio di 'transizione', al fine di vivere e essere accettati come persone del genere  sperimentato, attraverso trattamenti ormonali, interventi chirurgici o altri servizi sanitari per far sì  che il corpo dell'individuo si allineino, nella misura desiderata e possibile, con il genere  sperimentato
#+END_QUOTE

I criteri diagnostici nel DSM-5 per la disforia di genere in adulti e adolescenti:
A. Una marcata incongruenza tra il genere esperito/espresso da un individuo e  le caratteristiche sessuali e il genere assegnato, della durata di almeno 6 mesi, che si  manifesta attraverso almeno due dei seguenti criteri:
   1. Una marcata incongruenza tra il genere esperito/espresso da un individuo e le  caratteristiche sessuali primarie e/o secondarie (o negli adolescenti, le  caratteristiche sessuali secondarie attese).
   2. Un forte desiderio di liberarsi delle proprie caratteristiche sessuali primarie e/o  secondarie  a  causa  di  una  marcata  incongruenza  con  il  genere  esperito/espresso di un individuo (o nei giovani adolescenti, un desiderio di  impedire lo sviluppo delle caratteristiche sessuali secondarie attese).
   3. Un forte desiderio per le caratteristiche sessuali primarie e/o secondarie del  genere opposto.
   4. Un forte desiderio di appartenere al genere opposto (o un genere alternativo  diverso dal genere assegnato).
   5. Un forte desiderio di essere trattato come appartenente al genere opposto (o un  genere alternativo diverso dal genere assegnato).
   6. Una forte convinzione di avere i sentimenti e le reazioni tipici del genere opposto  (o di un genere alternativo diverso dal genere assegnato).
B. la condizione è associata a sofferenza clinicamente significativa o a  compromissione del funzionamento in ambito sociale, lavorativo o altre aree  importanti.

Negli adulti si può aggiungere la specifica "post-transizione", facendo così riferimento ad un inviduo che è passato a vivere completamente nel genere esperito, che si è sottoposto, o sta per sottoporsi, ad un trattamento, ormonale o chirurgico, di affermazione di genere

**** Diagnosi Differenziale
Il DSM-5-TR indica cinque principali condizioni da tenere in considerazione quando si fa diagnosi di disforia di genere [cite:@american_psychiatric_association_diagnostic_2022]

# qua tesi alessiomarrucci cita un libro che però non so bene che roba sia e fa una differenziale diversa dal dsm
# io ho riportato il DSM-TR che sono finalmente riuscito a scaricare → valuto eventuali aggiunte per le varie entry

- *Nonconformità ai ruoli di genere*: \\
  Individui i quali si comportano in modo non conforme a quelli che sono li stereotipi che caratterizzano il proprio ruolo di genere. In questo caso non è presente il forte desiderio di essere dell'altro genere e soprattutto non è presente l'alto livello di sofferenza che caratterizza la disforia

- *Disturbo da travestitismo*: \\
  Disturbo parafiliaco tipicamente caratteristico di individui maschi adulti che provano eccitazione sessuale nell'indossare un vestiario tipicamente femminile, l'eccitazione è associata ad angoscia che però non comprende dubbi riguardo la propria identità di genere.
  Non è raro questo disturbo sia diagnosticato e coesista insieme ad una disforia di genere, di cui talvolta può essere un precursore.

- *Disturbo da dismorfismo corporeo*: \\
  Individui con questo disturbo percepiscono parti del loro corpo come anomale ed hanno il desiderio di alterarele o rimuoverle.
  Questo disturbo può comprendere gli organi genitali o altre carattersitiche sessuali, motivo per cui potrebbe essere confuso con una disforia di genere, in questo caso tuttavia il disturbo è correlato alla parte del corpo in sé e non mette in discussione la propria identità di genere.
   questa seconda frase non è propriamente detta nel dsm


- *Disturbi dello spettro autistico*: \\
  Negli indivudui con disturbo dello spettro autistico può essere difficile differenzia una disforia di genere da una preoccupazione autistica derivante da una visione rigida riguardo i ruoli di genere e/o difficoltà tipiche dello spettro autistico a comprendere le relazioni sociali.



- *Schizofrenia e altri disturbi psicotici*: \\
  Nella schizofrenia possono essere presenti deliri riguardo l'appartenere ad un altro genere. Deliri che includono il tema del genere possono presentarsi in fino al 20% degli individui con schizofrenia.
  Uno studio ha dimostrato la presenza di disturbi neurobiologici dello sviluppo comuni che potrebbero essere determinanti in entrambe le condizioni [cite:@rajkumar_gender_2014]; tuttavia review più recenti in letteratura dimostrano come l'incidenza della schizofrenia non sia maggiore in individui transgender rispetto alla popolazione generale [cite:@dhejne_mental_2016]
  # non sono sicuro che mi piaccia molto questa cosa perché il primo parla di disforia e il secondi di popolazione trans quindi teoricamente il secondo non nega il primo, però aggiunge contesto.
  È molto importante distinguere situazioni in cui le due condizioni coesistono da quelle in cui i disturbi sono unicamente dovuti al quadro schizofrenico, in quanto questo ha un impatto importante sulla gestione del paziente e sull'approccio terapeutico, specialmente prendendo in considerazione trattamenti molto invasivi come la riassegnazione chirurgica del sesso. [cite:@stusinski_gender_2018]
  # maybe snellire un po'questa frase
  Tipicamente le due condizioni si possono differenziare dato che il contenuto dei deliri è bizzaro e questi fluttuano in corrispondenza con remissioni ed ricomparsa degli episodi psicotici.
  Un ulteriore fattore che può aiutare nella diagnosi è l'utilizzo di farmaci antipsicotici i quali, nel caso dei pazienti psicotici, portano ad una scomparsa del pensiero transessuale.[cite:@urban_[transsexualism_2009]



# *Altre presentazioni cliniche*: → volendo ci sono anche queste nel DSM però penso di evitare mi sembrauno un po'inutili


Altre condizioni che possono presentare problemi di diagnosi differenziale non prese in considerazione nel DSM-5-TR comprendono:
# qua se le voglio tenere devo spiegarle un po'meglio

# alessiomarrucci
- Sviluppo atipico dell'Identità di Genere
- Disforia di Genere Transitoria Secondaria (abuso sessuale)

# lorenzoauricchio
- Omosessualità egodistonica e omofobia interiorizzata
- Disturbi dell'alimentazione
- Disturbo borderline di personalità


*** Presentazione Clinica (?)

*** Valutazione e approccio ad un individuo con incongruenza di genere

# domanda se posso citare gli SOC tipo qua per l'intero paragrafo oltre a i punti in cui li cito esplicitamente perché la struttura generale di diverse cose è presa da quelli

La gestione di un individuo TGD non è compito semplice per il clinico, per questo motivo la /World Professional Association for Transgender Health/ (WPATH) stila un documento per stabilire quelle che sono le migliori pratiche cliniche da mettere in atto, questo è lo /Standards of Care of Transgender and Gender Diverse People/(SOC). [cite:@coleman_standards_2022]
La WPATH è un'organizzazione non-profit interdisciplinare professionale ed educativa, il cui scopo è quello di promuovere un alto standard di cura per tutta la popolazione TGD. [cite:@wpath_mission_nodate].
Gli SOC rappresentano un insieme di linee guida riconosciute a livello internazionale per la presa in carico di individui TGD, con l'obiettivo di portarli a raggiungere una situazione di salute a livello fisico e psicologico, l'ultima edizione pubblicata sono gli SOC-8 del 2022. \\

Queste raccomandazioni non sono pensate esclusivamente per i professionisti sanitari, difatti un intero capitolo è dedicato all'educazione per la popolazione generale, punto fondamentale per combattere contro la discriminazione ancora molto diffusa nei confronti degli individui TGD.
Atti di discrimniatori, di intolleranza e violenza nei confronti della popolazione TGD rappresentanto un fenomeno frequente, che impatta in modo importante la salute e la sicurezza di questi individui, con una percentuale di violenza riportata che arriva fino all'80% in alcune indagini[cite:@worldbank_life_2018].

Anche per quanto riguarda il personale sanitario, le competenze risultano spesso insufficienti, specialmente nel personale non specializzato [cite:@aldridge_understanding_2022], con una buona percentuale di persone TGD che riportano esplicitamente di evitare per quanto possibile l'utilizzo dei servizi sanitari per paura di essere discriminati o subire maltrattamenti [cite:@lerner_more_2021]. Questo risulta estremamente problematico, andando ad limitare e rendere più difficile l'accesso a terapie importanti di affermazione di genere e rendendo più difficoltosa la gestione di una condizione già intrinsecamente complessa[cite:@giffort_relationship_2016].


Gli SOC individuano un diverso approccio all'individuo TGD secondo l'età, esistono infatti linee guida separate per adulti, adolescenti e bambini.

Nell'adulto, il primo compito del professionista sanitario è di effettuare una corretta valutazione della presenza di incongruenza di genere e di identificare altre eventuali problematiche psichiatriche [cite:@coleman_standards_2022].
Successivamente è importante informare ed educare l'adulto TGD per quanto riguarda quelli che sono i possibili percorsi di affermazione di genere, sia medici che chirurgici, dato che è stato dimostrato da vari studi come questi abbiano un impatto positivo importante sulla salute mentale nei soggetti TGD[cite:@aldridge_longterm_2021], migliorando la qualità della vita, diminuendo i sintomi di ansia e depressione[cite:@nguyen_gender-affirming_2018] e il rischio suicidario[cite:@green_association_2022].

La decisione di intraprendere un percorso di affermazione di genere è un passo importante per l'individuo TGD ed una decisione che spesso viene presa in collaborazione con un profesionista sanitario [cite:@coleman_standards_2022], anche se in alcuni casi, solamente per le terapie ormonali, vengono utilizzati con successo dei modelli che prediligono la decisione dell'adulto TGD, tipicamente chiamati modelli a "consenso informato"[cite:@deutsch_use_2012][cite:@schulz_informed_2018].
In ogni caso è fondamentale assicurasi che il soggetto sia in grado di comprendere quali sono rischi e benefici del trattamento per essere in grado di dare il suo consenso [cite:@coleman_standards_2022], escludendo malattie mentali che possono interferire, in particolar modo sintomi di decadimento cognitivo o psicotici[cite:@hostiuc_testing_2018].

# volendo ho trovato il paragrafo di iniziarla solo quando è grave e che c'è benefici anche del farlo in modo profilattico, però non mi sembra una info particolarmente interessante

Un'altra parte importante del percorso di un individuo TGD è quella di transizione sociale, che può dare grande beneficio al soggetto, migliorandone la salute mentale e la qualità della vita[cite:@coleman_standards_2022].
Tuttavia, esistono anche circostanze in cui l'individuo non desidera effettuare la transizione sociale per varie motivazioni, spesso correlate ad una paura di abbandono da parte di amici e familiari,
*** BIA (?)

* Obiettivi

* Materiali e Metodi

* Risultati

* Discussione

* Conclusioni


* Bibliografia

#+cite_export: csl sources/american-medical-association.csl
#+print_bibliography:
