#+title: titolo
#+Author: Lorenzo Macelloni
#+bibliography: biblio.bib
#+latex_header: \usepackage[scaled]{inter} \renewcommand\familydefault{\sfdefault}


* Abstract

* Introduzione
*** termini - genere, sesso, disforia e incongruenza
Nella discussione di una condizione come l'Incongruenza di Genere (IG) è
opportuno prendere familiarità con una determinata terminologia. Spesso infatti
alcuni termini come "sesso" e "genere" vengono utilizzati in maniera
interscambiabile nel linguaggio comune, considerando quindi inevitabilmente
correlate quelle che sono le caratteristiche socioculturali e biologiche che
contraddistinguono uomo e donna.

# con gli studi di genere non è più così in breve → aggiungere questo
Vediamo quindi quelle che sono le definizioni date dall'NIH per questi concetti
[cite:@noauthor_sex_2022] [cite:@noauthor_sex_nodate] (non so se è redundant citare il secondo che è citato dal primo)

**** Sesso Biologico
Costrutto biologico utilizato per descrivere caratteristiche ormonali, genetiche, anatomiche e biologiche basilari.
Tipicamente è dicotomico, distingue le categorie maschio e femmina.
Tuttavia, esistono anche stati intersessuali, in cui i caratteri ed i cromosomi sessuali non sono definibili all'interno di una sola di queste categorie.

**** Genere (gender)
Costrutto multidimensionale sociale e culturale; comprende ruoli, attività, comportamenti ed espressioni, che sono tipicamente identificati all'interno di una determinata società come propriamente maschili o femminili.

Sulla base del genere si definisce l'*identità di genere*.
Questa è la sensazione individuale di sentirsi parte di una determinata categoria di genere, che può essere maschile, femminile, o stati alternativi e non-binari.
L'identità di genere è quindi auto-definita, può cambiare nel corso della vita e non corrisponde necessariamente a quelle che sono le aspettative sociali nei confronti del sesso dell'individuo.
# questa roba dell'identità poi ovviamente l'approfondisco nella parte sulla storia dell'IG no? cioé mi sembra inutile stare a fare troppa intro in questa parte solo di terminologia.
Queste costituiscono infatti il *ruolo di genere*, ovvero ciò che viene percepito all'interno di una determinata società come proprio di un certo genere, in termini di norme, comportamenti ed espressioni.
L'*espressione di genere* è quindi la modalità in cui l'individuo decide di mostrare la propra identità di genere attraverso carattersitiche esterne come il proprio abbigliamento, l'utilizzo di determinati pronomni...


**** Orientamento Sessuale [cite:@NAP26424]
# qua se ho un po'parlato della cosa in vari punti dove dovrei metterla la citazione? all'inizio? in un punto a caso?

L'orientamento sessuale è anch'esso un costrutto complesso che comprende l'attrazione romantica, emotiva e sessuale.
Fa riferimento quindi agli elementi esterni capaci di indurre una risposta nell'individuo.
È quindi definito solitamente sulla base del genere delle persone verso cui un indviduo prova attrazione sessuale o romantica, in rapporto al genere dell'individuo stesso.
# decisamente troppo convuluta sta frase

I termini più comuni che identificano l'orientamento sessuale di basano su una visione binaria del genere e distinguono quindi persone /eterosessuali/, /omosessuali/ e /bisessuali/.
In tempi relativamente recenti sono stati aggiunti termini che prendono in considerazione una visione più moderna e fluida del genere, come /pansessuale/ che indica un'attrazione verso gli altri che non dipende dal genere.

L'orientamento sessuale, inoltre, così come il genere, non è binario, ma costituisce uno spettro.
Il primo a prendere in considerazione questa caratteristica fluida della sessualità fu Alfred Kinsey, nel suo libro /Sexual Behavior in the Human Male/ del 1948, dove introduce la Scala di Kinsey [cite:@noauthor_kinsey_2024].
Questa definisce l'orientamento sessuale secondo un gradiente da 0, esclusiva eterossessualità, a 6, esclusiva omosessualità.

L'orientamento sessuale inoltre viene considerato fluido anche nel tempo, infatti questo può cambiare durante la vita di una persona anche in funzione delle circostanze dell'individuo.
# se ha senso aggiungere di più devo trovare un qualcosa di sensato da citare

# valutare se aggiungere la parte che divide l'orientamento in attrazione/identità/comportamento, a me sembra un po'overkill


*** definizione di incongruenza di genere
**** Varianza` o Non Conformità di Genere
**** Disforia di Genere
**** Transessuale
**** Transgender
**** Intersessuale
*** epidemiologia (o simili)
*** eziologia
*** diagnosi e criteri diagnostici
*** volendo comorbidità psichiatriche?
*** clinica
*** terapia

* Obiettivi  (?)

* Materiali e Metodi

* Risultati

* Discussione

* Conclusioni


* Bibliografia

#+cite_export: csl sources/american-medical-association.csl
#+print_bibliography:
